#############################################################################
# Makefile for building: dtbcoin
# Generated by qmake (2.01a) (Qt 4.8.6) on: ??? ?? 16 10:56:07 2015
# Project:  dtbcoin.pro
# Template: app
# Command: e:/deps/4.8.6/bin/qmake.exe -o Makefile dtbcoin.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = e:/deps/4.8.6/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = cp -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: dtbcoin.pro  ../4.8.6/mkspecs/default/qmake.conf ../4.8.6/mkspecs/features/device_config.prf \
		../4.8.6/mkspecs/qconfig.pri \
		../4.8.6/mkspecs/features/qt_functions.prf \
		../4.8.6/mkspecs/features/qt_config.prf \
		../4.8.6/mkspecs/win32-g++/qmake.conf \
		../4.8.6/mkspecs/win32-g++-4.6/qmake.conf \
		../4.8.6/mkspecs/features/exclusive_builds.prf \
		../4.8.6/mkspecs/features/default_pre.prf \
		../4.8.6/mkspecs/features/win32/default_pre.prf \
		../4.8.6/mkspecs/features/release.prf \
		../4.8.6/mkspecs/features/debug_and_release.prf \
		../4.8.6/mkspecs/features/default_post.prf \
		../4.8.6/mkspecs/features/win32/default_post.prf \
		../4.8.6/mkspecs/features/win32/rtti.prf \
		../4.8.6/mkspecs/features/win32/exceptions.prf \
		../4.8.6/mkspecs/features/win32/stl.prf \
		../4.8.6/mkspecs/features/static.prf \
		../4.8.6/mkspecs/features/warn_on.prf \
		../4.8.6/mkspecs/features/qt.prf \
		../4.8.6/mkspecs/features/win32/thread.prf \
		../4.8.6/mkspecs/features/moc.prf \
		../4.8.6/mkspecs/features/win32/windows.prf \
		../4.8.6/mkspecs/features/resources.prf \
		../4.8.6/mkspecs/features/uic.prf \
		../4.8.6/mkspecs/features/yacc.prf \
		../4.8.6/mkspecs/features/lex.prf \
		e:/deps/4.8.6/lib/qtmain.prl \
		e:/deps/4.8.6/lib/QtGui.prl \
		e:/deps/4.8.6/lib/QtNetwork.prl \
		e:/deps/4.8.6/lib/QtCore.prl
	$(QMAKE) -o Makefile dtbcoin.pro
../4.8.6/mkspecs/features/device_config.prf:
../4.8.6/mkspecs/qconfig.pri:
../4.8.6/mkspecs/features/qt_functions.prf:
../4.8.6/mkspecs/features/qt_config.prf:
../4.8.6/mkspecs/win32-g++/qmake.conf:
../4.8.6/mkspecs/win32-g++-4.6/qmake.conf:
../4.8.6/mkspecs/features/exclusive_builds.prf:
../4.8.6/mkspecs/features/default_pre.prf:
../4.8.6/mkspecs/features/win32/default_pre.prf:
../4.8.6/mkspecs/features/release.prf:
../4.8.6/mkspecs/features/debug_and_release.prf:
../4.8.6/mkspecs/features/default_post.prf:
../4.8.6/mkspecs/features/win32/default_post.prf:
../4.8.6/mkspecs/features/win32/rtti.prf:
../4.8.6/mkspecs/features/win32/exceptions.prf:
../4.8.6/mkspecs/features/win32/stl.prf:
../4.8.6/mkspecs/features/static.prf:
../4.8.6/mkspecs/features/warn_on.prf:
../4.8.6/mkspecs/features/qt.prf:
../4.8.6/mkspecs/features/win32/thread.prf:
../4.8.6/mkspecs/features/moc.prf:
../4.8.6/mkspecs/features/win32/windows.prf:
../4.8.6/mkspecs/features/resources.prf:
../4.8.6/mkspecs/features/uic.prf:
../4.8.6/mkspecs/features/yacc.prf:
../4.8.6/mkspecs/features/lex.prf:
e:\deps\4.8.6\lib\qtmain.prl:
e:\deps\4.8.6\lib\QtGui.prl:
e:\deps\4.8.6\lib\QtNetwork.prl:
e:\deps\4.8.6\lib\QtCore.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile dtbcoin.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
